describe('Teste para o site do Trabalho Pratico 1', () => {
    it('Testando criação de usuario', () => {
    cy.visit('https://automacaocombatista.herokuapp.com/treinamento/home')
    cy.get(':nth-child(1) > .collapsible-header').click()
    cy.get('.active > .collapsible-body > ul > :nth-child(1) > a').click()
    cy.get('#user_name').type('Igor')
    cy.get('#user_lastname').type('Villamarim')
    cy.get('#user_email').type('igor.dv@gec.inatel.br')
    cy.get('#user_address').type('Rua Roberto Resch 20')
    cy.get('#user_university').type('Inatel')
    cy.get('#user_profile').type('Estudante')
    cy.get('#user_gender').type('Homem')
    cy.get('#user_age').type('21')
    cy.get('.actions > input').click() 
    cy.get('.row.center').should('contain.text','Usuário Criado com sucesso')
  })
    it('Testando criação de usuario', () => {
    cy.visit('https://automacaocombatista.herokuapp.com/treinamento/home')
    cy.get(':nth-child(1) > .collapsible-header').click()
    cy.get('.active > .collapsible-body > ul > :nth-child(2) > a').click()
    cy.get(':nth-child(1) > :nth-child(10) > .material-icons').click()
    cy.get('#user_address').clear()
    cy.get('#user_address').type('Rua 3')
    cy.get('.actions').click()
    cy.get('.row.center').should('contain.text','Seu Usuário foi Atualizado!')
  })
    it('Testando criação de usuario invalido', () => {
    cy.visit('https://automacaocombatista.herokuapp.com/treinamento/home')
    cy.get(':nth-child(1) > .collapsible-header').click()
    cy.get('.active > .collapsible-body > ul > :nth-child(1) > a').click()
    cy.get('#user_name').type('Igor')
    cy.get('#user_lastname').type('Villamarim')
    cy.get('#user_email').type('igor.dvgec.inatel.br')
    cy.get('#user_address').type('Rua Roberto Resch 20')
    cy.get('#user_university').type('Inatel')
    cy.get('#user_profile').type('Estudante')
    cy.get('#user_gender').type('Homem')
    cy.get('#user_age').type('21')
    cy.get('.actions > input').click() 
    cy.get('h2').should('contain.text','error')
  })
    it('Clicando no Botão', () => {
    cy.visit('https://automacaocombatista.herokuapp.com/treinamento/home')
    cy.get(':nth-child(2) > .collapsible-header').click()
    cy.get('.active > .collapsible-body > ul > :nth-child(3) > a').click()
    cy.get('.btn-floating').click()
    cy.get('#div2 > h5').should('have.text','Você Clicou no Botão!')
  })
    it('Abrindo uma nova janela', () => {
    cy.visit('https://automacaocombatista.herokuapp.com/treinamento/home')
    cy.get(':nth-child(3) > .collapsible-header').click()
    cy.get('.active > .collapsible-body > ul > :nth-child(3) > a').click()
    cy.get('.btn').click()
  })
    it('Abrindo um link', () => {
    cy.visit('https://automacaocombatista.herokuapp.com/treinamento/home')
    cy.get(':nth-child(2) > .collapsible-header').click()
    cy.get('.active > .collapsible-body > ul > :nth-child(1) > a').click()
    cy.get(':nth-child(4) > :nth-child(1) > a').click()
    cy.get('.red-text').should('have.text','Bad Request!!')
  })
})